# Generated by Django 3.0 on 2020-07-07 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_computer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computer',
            options={'verbose_name': '电脑', 'verbose_name_plural': '电脑'},
        ),
    ]
